import type {
  OfficialResponse,
  PlaceWithCounts,
  PublicPlaceDetail,
  Review,
} from "@/lib/types";

export const DEMO_PLACES: PlaceWithCounts[] = [
  {
    id: "demo-place-1",
    name: "Cafe Lantern 池袋西口店",
    address: "東京都豊島区西池袋 1-12-1",
    nearest_station: "池袋駅 西口",
    lat: 35.7305,
    lng: 139.7074,
    area_tag: "東京都",
    status: "approved",
    moderation_note: null,
    created_at: "2026-03-08T09:00:00+09:00",
    approved_review_count: 2,
    latest_review_at: "2026-03-08T10:00:00+09:00",
  },
  {
    id: "demo-place-2",
    name: "なんばクイックダイナー",
    address: "大阪府大阪市中央区難波 3-2-1",
    nearest_station: "なんば駅",
    lat: 34.6663,
    lng: 135.5006,
    area_tag: "大阪府",
    status: "approved",
    moderation_note: null,
    created_at: "2026-03-05T09:00:00+09:00",
    approved_review_count: 1,
    latest_review_at: "2026-03-06T08:30:00+09:00",
  },
  {
    id: "demo-place-3",
    name: "北一コンビニ 札幌駅前店",
    address: "北海道札幌市中央区北五条西 2-1",
    nearest_station: "札幌駅",
    lat: 43.0687,
    lng: 141.3508,
    area_tag: "北海道",
    status: "approved",
    moderation_note: null,
    created_at: "2026-03-03T09:00:00+09:00",
    approved_review_count: 1,
    latest_review_at: "2026-03-04T20:10:00+09:00",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "demo-review-1",
    place_id: "demo-place-1",
    title: "研修は丁寧だったが、土日のシフト調整は急になりがち",
    body: "初日から3日間は先輩がついて研修してくれました。レジ説明やオーダーの流れは分かりやすかったです。一方で、土日のシフト変更は前日に連絡が来ることがあり、予定調整がやや大変でした。",
    tags: ["研修", "シフト"],
    rating: 3,
    status: "approved",
    author_id: "demo-author-1",
    author_ip: "127.0.0.1",
    author_ua: "demo",
    moderation_note: null,
    created_at: "2026-03-08T10:00:00+09:00",
  },
  {
    id: "demo-review-2",
    place_id: "demo-place-1",
    title: "ピーク帯は忙しいが、相談しやすい雰囲気",
    body: "夕方以降は一気に来客が増えます。最初は慌てましたが、困った時に店長へ相談しやすい雰囲気がありました。残業は締め作業が重なった日だけ15分ほどでした。",
    tags: ["人間関係", "残業"],
    rating: 4,
    status: "approved",
    author_id: "demo-author-2",
    author_ip: "127.0.0.1",
    author_ua: "demo",
    moderation_note: null,
    created_at: "2026-03-07T18:00:00+09:00",
  },
  {
    id: "demo-review-3",
    place_id: "demo-place-2",
    title: "忙しい時間は長いが、シフト相談には乗ってもらえた",
    body: "夕方から夜にかけて来客が多く、ピーク帯はかなり忙しかったです。一方で、学業との両立について相談した際は店長が週ごとにシフトを調整してくれました。閉店後の片付けで15分ほど残る日はありました。",
    tags: ["給与", "休憩"],
    rating: 3,
    status: "approved",
    author_id: "demo-author-3",
    author_ip: "127.0.0.1",
    author_ua: "demo",
    moderation_note: null,
    created_at: "2026-03-06T08:30:00+09:00",
  },
  {
    id: "demo-review-4",
    place_id: "demo-place-3",
    title: "研修手順が整理されていて、初日でも動きやすかった",
    body: "最初の2日間は動画とOJTがセットになっていて、レジや品出しの順番が分かりやすかったです。朝帯は少人数で慌ただしいですが、困ったときは社員がフォローに入ってくれました。休憩も比較的取りやすかったです。",
    tags: ["研修", "人間関係"],
    rating: 4,
    status: "approved",
    author_id: "demo-author-4",
    author_ip: "127.0.0.1",
    author_ua: "demo",
    moderation_note: null,
    created_at: "2026-03-04T20:10:00+09:00",
  },
];

export const DEMO_OFFICIAL_RESPONSES: OfficialResponse[] = [
  {
    id: "demo-response-1",
    place_id: "demo-place-1",
    body: "ご指摘ありがとうございます。現在はシフト確定を原則3日前までに行う運用へ変更しています。今後も改善状況を確認します。",
    status: "approved",
    moderation_note: null,
    contact_name: "店舗運営担当",
    contact_email: "ops@example.com",
    created_at: "2026-03-08T11:00:00+09:00",
  },
];

export const DEMO_PLACE_DETAILS: Record<string, PublicPlaceDetail> = {
  "demo-place-1": {
    place: DEMO_PLACES[0],
    reviews: DEMO_REVIEWS.filter((review) => review.place_id === "demo-place-1"),
    officialResponses: DEMO_OFFICIAL_RESPONSES.filter(
      (response) => response.place_id === "demo-place-1",
    ),
  },
  "demo-place-2": {
    place: DEMO_PLACES[1],
    reviews: DEMO_REVIEWS.filter((review) => review.place_id === "demo-place-2"),
    officialResponses: [],
  },
  "demo-place-3": {
    place: DEMO_PLACES[2],
    reviews: DEMO_REVIEWS.filter((review) => review.place_id === "demo-place-3"),
    officialResponses: [],
  },
};
